# Generated by Django 4.1.2 on 2022-10-09 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_hostname', models.CharField(max_length=250, verbose_name='主机hostname')),
                ('resource_ip', models.GenericIPAddressField(verbose_name='主机ip')),
                ('resource_port', models.SmallIntegerField(default=22)),
                ('resource_password', models.CharField(max_length=250, verbose_name='主机password')),
                ('resource_rsa', models.TextField(blank=True, verbose_name='Rsa密钥')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源池',
            },
        ),
    ]
