# Generated by Django 4.1.2 on 2022-10-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsmanage', '0002_alter_resource_resource_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_rsa',
            field=models.TextField(blank=True, verbose_name='主机Rsa密钥'),
        ),
    ]
